### ISSUE TITLE
Does not read values from the configuration file and some other related bugs

### ISSUE THREAD

**Issue by TheDirectorX** [MelanX/MoreVanillaLib#10]
- [x] The values of `chances.extraDropValue` and `chances.doubleDropValue` not read from the **config** file (_they do not change anything in the game_)

![image](https://user-images.githubusercontent.com/43481085/78588883-c8d3cb80-7858-11ea-9072-505ba44c6c07.png)
![image](https://user-images.githubusercontent.com/43481085/78589527-c3c34c00-7859-11ea-9c9a-3baf10db2915.png)
- [x] Also, the values in the JEI description do not change

### Other bugs:
- [x] **Not quite correctly written about the chance of an extra drop.** At first I thought that “_a 0.5% chance to get a piece of coal dropped_” refers to double drop, because there was no “extra drop” on the Coal Pickaxe. Maybe instead of "_a chance to get a piece of coal dropped_" was meant "_a chance to get a double drop_"?
- [x] And the last one where it says "_If you use this pickaxe, there is a..._" **shows all the tools**, not just the **pickaxe**

**Versions:**
- Forge Version: `31.1.35`
- Mod Version: `morevanillalib-1.15.2-1.1` `morevanillatools-1.15.2-2.0.2`

I suppose if #5 #6 #8  issues are closed, then they have been resolved?

**Comment by MelanX** [comment]
You're right, the text is still wrong. I forgot to change that. The values listed first are correctly read by the game. Did you generated a new world? Or did you change the config in the world folder? You need to do it because it's a server config. The config in ```defaultconfigs``` is only important if the config isn't in the world folder. 
I'm confused by double drop and extra drop... I try to figure out the problems. 
Yes, it shows all items and not just the pickaxe because it's much easier. Maybe I should improve the text but it will still be all tools of this material. 

What I'm confused very much about is that you have 3 pages in JEI and I only have two. This page from the screenshot is the missing one. And I don't know why xD That's odd but not your problem.. :D Thank you for reporting.

**Comment by TheDirectorX** [comment]
Well, yes, re-creating the world solved the problem. It's just that this TEST world has already tested many different mods, I forget to recreate it.  `¯\_(ツ)_/¯`
