### ISSUE TITLE
Not really an issue but something to know

### ISSUE THREAD

**Issue by TheonGray** [MelanX/MoreVanillaLib#18]
Hello!! The morevanillalib-1.16.2-1.2.12 version conflicts with another mod called Apotheosis version {1.16.3-4.3.1}. It never did this before and I know this isn't really this mods problem but just something to know. Minecraft 1.15.2 the mods ran just fine together, specifically morevanillalib-1.15.2-1.2.4 and Apotheosis-1.15.2-3.1.2 (:

**Comment by MelanX** [comment]
Which conflicts?

**Comment by TheonGray** [comment]
Here is the crash report ([Crash Report.txt](https://github.com/MelanX/MoreVanillaLib/files/5322432/Crash.Report.txt)). They were working fine together with the 1.15.2 versions of both mods however now with 1.16.3 they conflict. I'm not really great with this so I might be reading the Crash Report wrong.... Sorry if this is a waste of time...

**Comment by Bass2style** [comment]
Hi,

i reported that on Apotheosis Github, and Shadow Of Fire replyed me that it's caused by the method used to categorize tools if i have correctly understand.

you can find my report on ShadowOfFire's GIT here : https://github.com/Shadows-of-Fire/Apotheosis/issues/232

i try to collect logs, because i'm working on few issues on my pack, and i lost the latest impacted log.

edit : here is a crashlog : https://pastebin.com/YdikasHM

**Comment by Bass2style** [comment]
seems fixed with the last update. thanks.
