### ISSUE TITLE
extra drop doesn't work on other blocks than effective on blocks

### ISSUE THREAD

**Issue by MelanX** [MelanX/MoreVanillaLib#6]
Coal Hammer on Stone -> Extra Drop
Coal Hammer on Dirt -> only dirt drop

**Comment by TheUntamed** [comment]
Is the _morevanillalib-server_ configuration file supposed to be in the "config" or "defaultconfigs"/"serverconfig" folder?

**Comment by MelanX** [comment]
it should be in the serverconfig. I just put it in the normal config path for easily accessing it and modify.

**Comment by TheUntamed** [comment]
Maybe that's why it's not working. I changed the configs in the "config" folder and created a singleplayer world. Maybe the changes get overruled by the file in the "world"->"serverconfig" folder which is created on singleplayer world creation.
Maybe the config has to be in the "defaultconfig" folder to be accepted and not getting overruled by the file in the "serverconfig" folder.

**Comment by MelanX** [comment]
-> https://github.com/MelanX/MoreVanillaLib/issues/8 :)
